### ISSUE TITLE
Replacement of characters like `<` in passwords

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/pronamic-pay-ideal-2#6]
In internal support ticket https://secure.helpscout.net/conversation/2665775947/27547/ it occurred that characters like `<` are saved as `&lt;` in the gateway meta data. This results in SSL issues.

**Comment by rvdsteege** [comment]
This is caused by the `sanitize_text_field()` function when settings are saved:

- https://developer.wordpress.org/reference/functions/sanitize_text_field/
- https://github.com/pronamic/wp-pay-core/blob/8e50de8e7b89cdb77dbfbe324b0271b0637219df/src/Admin/AdminGatewayPostType.php#L417-L425

> ### Description
> - Checks for invalid UTF-8,
> - **Converts single `<` characters to entities**
> - Strips all tags
> - Removes line breaks, tabs, and extra whitespace
> - Strips percent-encoded characters

We could use `wp_specialchars_decode( $value )` when reading the value from the post meta. However, that would still strip percent-encoded characters, which is also not really practical (strips pattern `%[a-f0-9]{2}`) as `%` is a common character to use in passwords.

It might be better to either:
1. don't use `sanitize_text_field()` when saving passwords _or_
2. do not allow `<` and `%` characters for this setting.

Thoughts, @remcotolsma?

**Comment by remcotolsma** [comment]
> 1. don't use `sanitize_text_field()` when saving passwords _or_

As far as I'm concerned accepting the raw post data is acceptable in this case, WordPress itself seems to do this as well:

- https://github.com/WordPress/WordPress/blob/4fc2975cb5e5ff65bc70071491d41ccdcb84b4fb/wp-login.php#L994C4-L994C18
- https://github.com/WordPress/WordPress/blob/4fc2975cb5e5ff65bc70071491d41ccdcb84b4fb/wp-includes/user.php#L3337-L3368

In the following library we have a custom input function in place for this:

https://github.com/pronamic/wp-pronamic-pay-ideal-advanced-v3/blob/7370590f3710a7d9c62172805b8e1241feb7bc4b/src/Integration.php#L173-L194
